name: Deploy to EC2 via AWS CLI

on:
  pull_request:
    branches:
      - dev
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Zip application code
      run: |
        zip -r app.zip . -x ".git/*" ".github/*"

    - name: Upload zip to S3
      run: |
        aws s3 cp app.zip s3://bioradcicdpipeline/app-dev.zip
      # Optional: Replace with your bucket name

    - name: Trigger SSM command on EC2
      run: |
        aws ssm send-command \
          --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy dev branch code" \
          --parameters 'commands=[
            "aws s3 cp s3://bioradcicdpipeline/app-dev.zip ~/app.zip",
            "unzip -o ~/app.zip -d ~/dev-code"
          ]' \
          --region ${{ secrets.AWS_REGION }}

